### ISSUE TITLE
Nextjs SSR app shows "Page Not Found" if I deploy it with CLI

### ISSUE THREAD

**Issue by teddybee** [netlify-templates/next-netlify-starter#47]
I have issues with several projects when I would like to deploy my sites via netlify-cli. The deploy seemed successful, but always got "Page not found". 

The steps that I did:
- Checkout this template
- yarn install
- yarn build
- make a new project with netlify console
- netlify link
- netlify deploy --prod

I have tried also the _redirection trick that SPA React projects need, without success.

The temporary project`s url is:
[https://roaring-melomakarona-4fbe5a.netlify.app/](https://roaring-melomakarona-4fbe5a.netlify.app/)

**Comment by maxcell** [comment]
Howdy @teddybee! This is definitely a rare bug! I got lots of questions and hopefully they can lead us to the solution!

Beyond checking this project out, what are other customizations are you potentially making to the configuration? Possibly either the `netlify.toml` or the `next.config.js`? Or are you just using `getServerSideProps` and that's not working?

**Comment by teddybee** [comment]
Hi @maxcell,
I have done nothing. My other projects has also problems with cli deploy, that's why I tried out the "factory" project.

Also there is a huge bug with nextjs and lambda functions. The scheduled runnning is not firing events at all. I don't know where to report that.

**Comment by teddybee** [comment]
@maxcell The code itself that I tried second time is i this particular repository. I checked out his and it isn`t working via cli deploy.
The netlify deploy is here: [https://roaring-melomakarona-4fbe5a.netlify.app/](https://roaring-melomakarona-4fbe5a.netlify.app/)

**Comment by maxcell** [comment]
@teddybee Ahhhh I read your producing steps and I think the problem is that `yarn build` isn't enough for deploying to Netlify. If you're doing manual deploys with this project, you're going to need to actually run `netlify deploy --prod --build` this telling Netlify to build locally before deploying the project.

The reason why `yarn build` isn't enough is because that doesn't produce the necessary Netlify Functions for SSR to work for Next.

So steps you'll want to do:
- 1. First, remove the `netlify-cypress-plugin` information in your `netlify.toml` (if it is there)
- 2. Then in your terminal make sure to run `netlify deploy --prod --build`

---

Now if you don't want to do this, my recommendation is your netlify site should connect to your GitHub project to make sure it automatically does all of this for you!
